config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  get 'top/main'
  root 'top#main'
#  root 'products#index'
  resources :products
  resources :cart_items, only: [:new, :create, :destroy]
  resources :carts, only: [:show]  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cartitems
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :price, presence: true
    has_one :cartitem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
private
    def current_cart
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
    helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    def new
        @cartitem = Cartitem.new(product_id: params[:product_id])
    end
    def create
        logger.debug "--" + params[:cartitem][:product_id]
        @cartitem = Cartitem.new(product_id: params[:cartitem][:product_id], 
        qty: params[:cartitem][:qty], cart_id: current_cart.id)
        if @cartitem.save
          flash[:info] = 'カートに商品を追加しました'
          redirect_to carts_show_path
        else
          render 'new'
        end    
    end
    def destroy
        cartitem = Cartitem.find(params[:id])
        cartitem.destroy
        redirect_to carts_show_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cartitems = current_cart.cartitems
    #item.where(cart_id: current_cart.id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.create(name: params[:product][:name], price: params[:product][:price])
    if @product.save
      flash[:info] = '商品を登録しました'
      redirect_to products_path
    else
      render 'new'
    end    
  end
  
  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/new.html.erb
<%
  if @cartitem.errors.present?
    @cartitem.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
<% end %>

<%= form_for @cartitem, url: {action: :create} do |f| %>
  <p>商品名：<%= Product.find(@cartitem.product_id).name %></p>
  <p>価格：<%= Product.find(@cartitem.product_id).price %>円</p>
  <%= f.hidden_field :product_id %> </p>
  <p><%= f.label :qty, '数量' %> 
  <%= f.text_field :qty %> </p>
  <p><%= f.submit '登録' %></p>
<% end %>

app/views/carts/show.html.erb
<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>

<% sum = 0 %>

<% @cartitems.each do |e| %>
    <p>
    <%= e.product.name %>
    <%= e.product.price %>円
    <%= e.qty %>
    <%= link_to 'カートから削除する', cart_item_path(e), method: :delete %>
    </p>
    <% sum += (e.product.price.to_i * e.qty.to_i) %>
<% end %>

<p>
    合計金額：<%= sum %>円
<p>
    <%= link_to '商品一覧ページ', root_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>

<% @products.each do |e| %>
  <p>
    <%= e.name %>
    <%= e.price %>円
    <%= link_to '削除', product_path(e), method: :delete %>
    <%= link_to 'カートに入れる', new_cart_item_path(product_id: e.id) %>
  </p>
<% end %>

<p> 
  <%= link_to '商品を新規登録する', new_product_path %>
</p>
<p>
    <%= link_to 'カートを見る', carts_show_path %>
</p>

app/views/products/new.html.erb
<%
  if @product.errors.present?
    @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
<% end %>

<%= form_for @product, url: {action: :create} do |f| %>
  <%= f.label :name, '商品名' %> 
  <%= f.text_field :name %> 
  <%= f.label :price, '価格' %> 
  <%= f.text_field :price %> 
  <%= f.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>